# Generated by Django 5.1.2 on 2025-03-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
    ]
