# Generated by Django 5.1.2 on 2025-03-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
