# Generated by Django 5.1.2 on 2025-03-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(choices=[('none', 'None'), ('programming', 'Programación'), ('math', 'Matemáticas'), ('english', 'Inglés')], default='none', max_length=20),
        ),
    ]
